import React, { useState } from 'react'
import {useNavigate} from 'react-router-dom'

import { preview } from '../assets'
import { getRandomPrompt } from '../utils'
import { FormField, Loader } from '../components'

const CreatePost = () => {
  const navigate = useNavigate()
  const [form, setForm] = useState({
    name: '',
    prompt: '',
    photo: ''
  })
  const [generatingImg, setGeneratingImg] = useState(false)
  const [loading, setLoading] = useState(false)

  const handleSubmit = () => {

  }

  const handleChange = (e) => {

  }

  return (
    <section className="max-w-7xl mx-auto">
        <div>
            <h1 className="font-extrabold text-[#222328] text-[32px]">
                Create
            </h1>
            <p className="mt-2 text-[666e75] text-[16px] max-w[500px]">
                Create imaginative image generated by DALL-E AI
            </p>
        </div>
        <form onSubmit={handleSubmit} className="mt-16 max-w-3xl">
            <div className="flex flex-col gap-5">
                <FormField 
                    labelName="YourName"
                    type="text"
                    name="name"
                    placeholder="JohnDoe"
                    value={form.name}
                    handleChange={handleChange}
                />
                <FormField 
                    labelName="Prompt"
                    type="text"
                    name="prompt"
                    placeholder="3D render of a cute tropical fish in an aquarium on a dark blue background, digital art"
                    value={form.prompt}
                    handleChange={handleChange}
                    isSurpriseMe
                    handleSurpriseMe={handleSurpriseMe}
                />
            </div>
        </form>
    </section>
  )
}

export default CreatePost